spring:
  application:
    name: accessguard-core
  datasource:
    url: jdbc:postgresql://localhost:5432/accessguard_core
    username: accessguard
    password: accessguard
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
  config:
    import: "classpath:security-jwt.yml"

logging:
  level:
    org.springframework.security: DEBUG
    org.flywaydb: INFO

security:
  jwt:
    public-key: file:dev-keys/dev-public.pem

  internal-jwt:
    private-key: file:dev-keys/dev-private.pem
    issuer: ${SECURITY_INTERNAL_JWT_ISSUER:accessguard-dev}
    subject: ${SECURITY_INTERNAL_JWT_SUBJECT:accessguard-core}